# Generated by Django 5.0.3 on 2024-03-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('steps', models.TextField()),
                ('cooktime', models.CharField(max_length=250)),
                ('method', models.CharField(max_length=250)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
            ],
        ),
    ]
