# Generated by Django 5.0.3 on 2024-03-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='method',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_style',
            field=models.IntegerField(choices=[(1, 'Grilled'), (2, 'Smoked')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='food_type',
            field=models.IntegerField(choices=[(1, 'Seafood'), (2, 'Pork'), (3, 'Beef')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='skill_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Expert')], default=1, null=True),
        ),
    ]
