# Generated by Django 5.0.3 on 2024-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='food_type',
            field=models.IntegerField(choices=[(1, 'Seafood'), (2, 'Pork'), (3, 'Beef'), (4, 'Poultry')], default=1, null=True),
        ),
    ]
