# Generated by Django 5.0.3 on 2024-03-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='food_type',
            field=models.IntegerField(choices=[(1, 'Seafood'), (2, 'Pork'), (3, 'Beef'), (4, 'Poultry'), (5, 'Pizza')], default=1, null=True),
        ),
    ]
