# Generated by Django 5.0.3 on 2024-04-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
